# Generated by Django 4.1.1 on 2023-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_user_rgp_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rgp',
            name='department',
            field=models.CharField(choices=[('admin', 'admin'), ('HR', 'HR'), ('QA', 'QA'), ('QC', 'QC'), ('PH', 'PH'), ('WH', 'WH'), ('ENGG', 'ENGG'), ('API', 'API'), ('ADL', 'ADL'), ('EOHS', 'EOHS'), ('IT', 'IT')], max_length=100, null=True),
        ),
    ]
