# Generated by Django 4.1.6 on 2023-10-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_nrgp_entry_nrgp_main_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_edit', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_edit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='reason_edit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='reason_edit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rgp_edit', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_edit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
