# Generated by Django 4.1.1 on 2023-11-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_nrgp_entry_nrgp_edit_nrgp_entry_nrgp_edit_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_trn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(choices=[('operator', 'operator'), ('manager', 'manager'), ('approver', 'approver'), ('verifier', 'verifier')], max_length=100)),
                ('department', models.CharField(choices=[('admin', 'admin'), ('HR', 'HR'), ('QA', 'QA'), ('QC', 'QC'), ('PH', 'PH'), ('WH', 'WH'), ('ENGG', 'ENGG'), ('API', 'API'), ('ADL', 'ADL'), ('EOHS', 'EOHS'), ('IT', 'IT')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nrgp_entry',
            name='nrgp_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_approver', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='nrgp_entry',
            name='nrgp_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='nrgp_entry',
            name='nrgp_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_edit', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='nrgp_entry',
            name='nrgp_outward_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_outward_sender', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='nrgp_entry',
            name='nrgp_verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_verifier', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='rgp_entry',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='rgp_entry',
            name='inward_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_receiver', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='rgp_entry',
            name='outward_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_sender', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='rgp_entry',
            name='rgp_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='rgp_entry',
            name='rgp_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rgp_edit', to='myapp.user_trn'),
        ),
        migrations.AlterField(
            model_name='rgp_entry',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='myapp.user_trn'),
        ),
        migrations.DeleteModel(
            name='User_rgp',
        ),
    ]
