# Generated by Django 4.1.1 on 2023-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_user_trn_alter_nrgp_entry_nrgp_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_trn',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
