# Generated by Django 4.1.1 on 2023-11-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_user_trn_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rgp_entry',
            new_name='Trn_entry',
        ),
        migrations.RenameModel(
            old_name='Nrgp_entry',
            new_name='Unsd_entry',
        ),
    ]
