# Generated by Django 4.1.1 on 2024-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_trn_entry_trn_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_edit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
