# Generated by Django 4.1.1 on 2024-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_trn_entry_trn_edit_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trn_entry',
            old_name='trn_update_time',
            new_name='trn_attend_time',
        ),
        migrations.AddField(
            model_name='trn_entry',
            name='mode_trn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trn_entry',
            name='type_trn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
