# Generated by Django 4.1.1 on 2024-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_trn_update_time_trn_entry_trn_attend_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
