# Generated by Django 4.1.1 on 2024-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_trn_entry_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
