# Generated by Django 4.1.1 on 2024-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_trn_entry_trn_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
