# Generated by Django 4.1.1 on 2024-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_trn_entry_trn_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='eva_voice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
