# Generated by Django 4.1.1 on 2024-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_rename_eva_voice_trn_entry_viva_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='sop_assign_time',
            field=models.DateTimeField(null=True),
        ),
    ]
