# Generated by Django 4.1.1 on 2024-03-22 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_unsd_entry_mode_trn_unsd_entry_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsd_entry',
            name='sop_name',
            field=models.CharField(default=datetime.datetime(2024, 3, 22, 6, 6, 47, 326606, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsd_entry',
            name='sop_no',
            field=models.CharField(default=datetime.datetime(2024, 3, 22, 6, 6, 55, 771986, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
