# Generated by Django 4.1.1 on 2024-03-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_unsd_entry_sop_name_unsd_entry_sop_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='sop_no',
            new_name='sop_num',
        ),
    ]
