# Generated by Django 4.1.1 on 2024-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_unsd_entry_sop_name_remove_unsd_entry_sop_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_asgn_status',
            field=models.BooleanField(default=False),
        ),
    ]
