# Generated by Django 4.1.1 on 2024-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_trn_entry_trn_attend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_edit_status',
            field=models.BooleanField(default=False),
        ),
    ]
