# Generated by Django 4.1.1 on 2024-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_trn_entry_trn_one_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trn_entry',
            name='trn_one_status',
            field=models.BooleanField(default=True),
        ),
    ]
