# Generated by Django 4.1.1 on 2024-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_alter_trn_entry_trn_one_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
