# Generated by Django 4.1.1 on 2024-03-23 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_trn_entry_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trn_entry',
            name='emp_name',
            field=models.CharField(default=datetime.datetime(2024, 3, 23, 10, 40, 43, 762936, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
