# Generated by Django 4.1.1 on 2024-03-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_alter_trn_entry_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
