# Generated by Django 4.1.1 on 2024-03-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_trn_entry_trn_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='myapp.user_trn'),
        ),
        migrations.AddField(
            model_name='trn_entry',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='myapp.user_trn'),
        ),
    ]
