# Generated by Django 4.1.1 on 2024-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_trn_entry_manager_trn_entry_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_approve_time',
            field=models.DateTimeField(null=True),
        ),
    ]
