# Generated by Django 4.1.1 on 2024-03-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_remove_unsd_entry_unsd_attend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsd_entry',
            name='unsd_end_time',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='unsd_start_time',
        ),
    ]
