# Generated by Django 4.1.1 on 2024-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_remove_unsd_entry_unsd_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='trn_evalu_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unsd_entry',
            name='unsd_evalu_time',
            field=models.DateTimeField(null=True),
        ),
    ]
