# Generated by Django 4.1.1 on 2024-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_trn_entry_trn_evalu_time_unsd_entry_unsd_evalu_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsd_entry',
            name='unsd_exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
