# Generated by Django 4.1.1 on 2024-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_trn_entry_emp_name_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsd_entry',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
