# Generated by Django 4.1.1 on 2024-04-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_remove_trn_entry_type_trn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trn_entry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='inward_mode',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='inward_party_challan',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='inward_receiver',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='inward_status',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='made_on',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='outward_mode',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='outward_reciever_name',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='outward_sender',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='outward_status',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='reason_edit',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_approve_time',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_created',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_edit',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_edit_time',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_inward_time',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_outward_time',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='rgp_serial',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='spname',
        ),
        migrations.RemoveField(
            model_name='trn_entry',
            name='unit',
        ),
    ]
