# Generated by Django 4.1.1 on 2024-04-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_remove_trn_entry_date_remove_trn_entry_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='rgp_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_trn'),
        ),
    ]
