# Generated by Django 4.1.1 on 2024-04-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_trn_entry_rgp_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trn_entry',
            old_name='rgp_created',
            new_name='trn_created',
        ),
    ]
