# Generated by Django 4.1.1 on 2024-04-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_rename_rgp_created_trn_entry_trn_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_created',
            new_name='unsd_created',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='made_on',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_edit',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_edit_time',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_main_serial',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_outward_mode',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_outward_reciever_name',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_outward_sender',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_outward_status',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_outward_time',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='nrgp_serial',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='reason_edit',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='spname',
        ),
        migrations.RemoveField(
            model_name='unsd_entry',
            name='unit',
        ),
    ]
