# Generated by Django 4.1.1 on 2024-04-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_rename_nrgp_created_unsd_entry_unsd_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_verifier',
            new_name='unsd_verifier',
        ),
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_verify_status',
            new_name='unsd_verify_status',
        ),
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_verify_time',
            new_name='unsd_verify_time',
        ),
    ]
