# Generated by Django 4.1.1 on 2024-04-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_rename_nrgp_verifier_unsd_entry_unsd_verifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_approve_status',
            new_name='unsd_approve_status',
        ),
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_approve_time',
            new_name='unsd_approve_time',
        ),
        migrations.RenameField(
            model_name='unsd_entry',
            old_name='nrgp_approver',
            new_name='unsd_approver',
        ),
    ]
