# Generated by Django 4.1.1 on 2024-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_rename_nrgp_approve_status_unsd_entry_unsd_approve_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_trn',
            name='department',
            field=models.CharField(choices=[('admin', 'admin'), ('HR', 'HR'), ('QA', 'QA'), ('QC', 'QC'), ('PH', 'PH'), ('WH', 'WH'), ('ENGG', 'ENGG'), ('API', 'API'), ('ADL', 'ADL'), ('EOHS', 'EOHS'), ('IT', 'IT'), ('NONE', 'NONE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_trn',
            name='usertype',
            field=models.CharField(choices=[('operator', 'operator'), ('manager', 'manager'), ('approver', 'approver'), ('verifier', 'verifier'), ('disable', 'disable')], max_length=100),
        ),
    ]
