# Generated by Django 4.1.1 on 2024-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_sop_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_master',
            name='current_status',
            field=models.CharField(default='Entry', max_length=10),
        ),
    ]
