# Generated by Django 4.1.1 on 2024-04-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_sop_master_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_master',
            name='trn_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_trn'),
        ),
    ]
