# Generated by Django 4.1.1 on 2024-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_sop_master_trn_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('emp_code', models.CharField(default=None, max_length=45, null=True)),
                ('in_time', models.DateTimeField(default=None, null=True)),
                ('out_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'punch_data',
            },
        ),
    ]
