# Generated by Django 4.1.1 on 2024-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_punchdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='atteninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttenID', models.CharField(max_length=20)),
                ('empcode', models.CharField(max_length=20)),
                ('intime', models.DateField()),
                ('outtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='device_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicelogsid', models.CharField(max_length=20)),
                ('empcode', models.CharField(max_length=20)),
                ('logdatetime', models.DateField()),
                ('direction_type', models.CharField(max_length=20)),
                ('trn_flag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='devicelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_name', models.CharField(max_length=20)),
                ('IPAddress', models.CharField(max_length=20)),
                ('Logs', models.CharField(max_length=20)),
                ('direction_type', models.CharField(max_length=20)),
            ],
        ),
    ]
