# Generated by Django 4.1.1 on 2024-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_atteninfo_device_logs_devicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_entry',
            name='sop_create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
