from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('back/', views.back, name='back'),
    path('new_password/', views.new_password, name='new_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('trn_signup/', views.trn_signup, name='trn_signup'),
#     path('rgp_search/', views.rgp_search, name='rgp_search'),
    path('trn_view/', views.trn_view, name='trn_view'),
    path('trn_all/', views.trn_all, name='trn_all'),
#     path('rgp_view_operator/', views.rgp_view_operator, name='rgp_view_operator'),
    path('trn_print/<int:pk>', views.trn_print, name='trn_print'),
    path('trn_exit/<int:pk>', views.trn_exit, name='trn_exit'),
#     path('rgp_outward/<int:pk>', views.rgp_outward, name='rgp_outward'),
#     path('rgp_inward/<int:pk>', views.rgp_inward, name='rgp_inward'),
    path('unsd_exit/<int:pk>', views.unsd_exit, name='unsd_exit'),
    path('unsd_signup/', views.unsd_signup, name='unsd_signup'),
    path('unsd_view/', views.unsd_view, name='unsd_view'),
    path('unsd_all/', views.unsd_all, name='unsd_all'),
    path('unsd_print/<str:pk>', views.unsd_print, name='unsd_print'),
#     path('nrgp_outward/<int:pk>', views.nrgp_outward, name='nrgp_outward'),
#     path('nrgp_view_operator/', views.nrgp_view_operator,
#          name='nrgp_view_operator'),
    path('<id>/update', views.update_view),
    # path('<id>/update', views.update_view_nrgp ),
    path('send_email/<int:pk>', views.send_email, name='send_email'),
    path('unsd_send_email/<int:pk>', views.unsd_send_email, name='unsd_send_email'),
    path('send_email_verify/<int:pk>',
         views.send_email_verify, name='send_email_verify'),

#     path('unsd_send_email_verify/<int:pk>',
#          views.unsd_send_email_verify, name='unsd_send_email_verify'),

    path('unsd_send_email_verify/<int:pk>>',
         views.unsd_send_email_verify, name='unsd_send_email_verify'),
    path('verify_link/<int:ver>/<int:pk>/<int:status>',
         views.verify_link, name='verify_link'),
    path('unsd_verify_link/<int:ver>/<int:pk>/<int:status>',
         views.unsd_verify_link, name='unsd_verify_link'),
    path('unsd_verify_link_all/<int:ver>/<str:pk>/<int:status>',
         views.unsd_verify_link_all, name='unsd_verify_link_all'),
    path('send_email_approve/<int:pk>',
         views.send_email_approve, name='send_email_approve'),

    path('unsd_send_email_approve/<int:pk>',
         views.unsd_send_email_approve, name='unsd_send_email_approve'),

    path('approve_link/<int:apr>/<int:pk>/<int:status>',
         views.approve_link, name='approve_link'),

    path('unsd_approve_link/<int:apr>/<int:pk>/<int:status>',
         views.unsd_approve_link, name='unsd_approve_link'),
    path('unsd_approve_link_all/<int:apr>/<str:pk>/<int:status>',
         views.unsd_approve_link_all, name='unsd_approve_link_all'),
         
    path('ajax/validate_email/', views.validate_email, name='validate_email'),
    path('log_print/<int:pk>', views.log_print, name='log_print'),
    path('serial_generate/', views.serial_generate, name='serial_generate'),

    path('trn_edit/<int:pk>', views.trn_edit, name='trn_edit'),
    path('unsd_edit/<int:pk>', views.unsd_edit, name='unsd_edit'),
#     path('trn_assign/<int:pk>', views.trn_assign, name='trn_assign'),
     path('trn_assign/<int:pk>',
         views.trn_assign, name='trn_assign'),
     path('un_trn_assign/<int:pk>',
         views.un_trn_assign, name='un_trn_assign'),
   path('trn_attend/<int:pk>', views.trn_attend, name='trn_attend'),
   path('untrn_view/<int:pk>', views.untrn_view, name='untrn_view'),
   path('back_assign/', views.back_assign, name='back_assign'),
   path('back_assign_unsd/', views.back_assign_unsd, name='back_assign_unsd'),
   path('trn_start/<int:pk>', views.trn_start, name='trn_start'),
   path('trn_end/<int:pk>', views.trn_end, name='trn_end'),
   path('trn_evaluation/<int:pk>', views.trn_evaluation, name='trn_evaluation'),
   path('trn_written/', views.trn_written, name='trn_written'),
    path('unsd_start/<int:pk>', views.unsd_start, name='unsd_start'),
    path('unsd_end/<int:pk>', views.unsd_end, name='unsd_end'),
     path('unsd_evatuation/<int:pk>', views.unsd_evaluation, name='unsd_evaluation'),
      path('unsd_written/', views.unsd_written, name='unsd_written'),
   path('view_matrix/<int:pk>', views.view_matrix, name='view_matrix'),
   path('sop_in/', views.sop_in, name='sop_in'),
   path('sop_search/',views.sop_search,name='sop_search'),
   path('sop_create/<int:pk>', views.sop_create, name='sop_create'),


]
